ci(tests): #14: add a hash check for values in to-dos-api-cpp within the local-env repository so that the file is checked for changes during workflow execution

diff --git a/.github/workflows/e2e-tests-on-pull-request.yml b/.github/workflows/e2e-tests-on-pull-request.yml
--- a/.github/workflows/e2e-tests-on-pull-request.yml
+++ b/.github/workflows/e2e-tests-on-pull-request.yml
@@ -20,6 +20,16 @@ jobs:
         with:
           repository: TourmalineCore/to-dos-local-env
           ref: feature/add-to-dos-api-cpp-release
+      
+      - name: Verify values file checksum
+        run: |
+          ACTUAL=$(sha256sum deploy/values-to-dos-api-cpp.yaml.gotmpl | awk '{ print $1 }')
+          if [ "$ACTUAL" != "${{ vars.LOCAL_ENV_REPO_VALUES_TO_DOS_API_CPP_SHA256 }}" ]; then
+            echo "ERROR: checksum mismatch"
+            echo "Expected: ${{ vars.LOCAL_ENV_REPO_VALUES_TO_DOS_API_CPP_SHA256 }}"
+            echo "Actual:   $ACTUAL"
+            exit 1
+          fi
 
       - name: Deploy Local Env to Kind k8s
         uses: devcontainers/ci@v0.3
